// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package cache

//go:generate minimock -i stream_processor/internal/infra/data/cache.DBConn -o db_conn_mock_test.go -n DBConnMock -p cache

import (
	"net/http"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// DBConnMock implements DBConn
type DBConnMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDo          func(req *http.Request) (rp1 *http.Response, err error)
	funcDoOrigin    string
	inspectFuncDo   func(req *http.Request)
	afterDoCounter  uint64
	beforeDoCounter uint64
	DoMock          mDBConnMockDo
}

// NewDBConnMock returns a mock for DBConn
func NewDBConnMock(t minimock.Tester) *DBConnMock {
	m := &DBConnMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DoMock = mDBConnMockDo{mock: m}
	m.DoMock.callArgs = []*DBConnMockDoParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mDBConnMockDo struct {
	optional           bool
	mock               *DBConnMock
	defaultExpectation *DBConnMockDoExpectation
	expectations       []*DBConnMockDoExpectation

	callArgs []*DBConnMockDoParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// DBConnMockDoExpectation specifies expectation struct of the DBConn.Do
type DBConnMockDoExpectation struct {
	mock               *DBConnMock
	params             *DBConnMockDoParams
	paramPtrs          *DBConnMockDoParamPtrs
	expectationOrigins DBConnMockDoExpectationOrigins
	results            *DBConnMockDoResults
	returnOrigin       string
	Counter            uint64
}

// DBConnMockDoParams contains parameters of the DBConn.Do
type DBConnMockDoParams struct {
	req *http.Request
}

// DBConnMockDoParamPtrs contains pointers to parameters of the DBConn.Do
type DBConnMockDoParamPtrs struct {
	req **http.Request
}

// DBConnMockDoResults contains results of the DBConn.Do
type DBConnMockDoResults struct {
	rp1 *http.Response
	err error
}

// DBConnMockDoOrigins contains origins of expectations of the DBConn.Do
type DBConnMockDoExpectationOrigins struct {
	origin    string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDo *mDBConnMockDo) Optional() *mDBConnMockDo {
	mmDo.optional = true
	return mmDo
}

// Expect sets up expected params for DBConn.Do
func (mmDo *mDBConnMockDo) Expect(req *http.Request) *mDBConnMockDo {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("DBConnMock.Do mock is already set by Set")
	}

	if mmDo.defaultExpectation == nil {
		mmDo.defaultExpectation = &DBConnMockDoExpectation{}
	}

	if mmDo.defaultExpectation.paramPtrs != nil {
		mmDo.mock.t.Fatalf("DBConnMock.Do mock is already set by ExpectParams functions")
	}

	mmDo.defaultExpectation.params = &DBConnMockDoParams{req}
	mmDo.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDo.expectations {
		if minimock.Equal(e.params, mmDo.defaultExpectation.params) {
			mmDo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDo.defaultExpectation.params)
		}
	}

	return mmDo
}

// ExpectReqParam1 sets up expected param req for DBConn.Do
func (mmDo *mDBConnMockDo) ExpectReqParam1(req *http.Request) *mDBConnMockDo {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("DBConnMock.Do mock is already set by Set")
	}

	if mmDo.defaultExpectation == nil {
		mmDo.defaultExpectation = &DBConnMockDoExpectation{}
	}

	if mmDo.defaultExpectation.params != nil {
		mmDo.mock.t.Fatalf("DBConnMock.Do mock is already set by Expect")
	}

	if mmDo.defaultExpectation.paramPtrs == nil {
		mmDo.defaultExpectation.paramPtrs = &DBConnMockDoParamPtrs{}
	}
	mmDo.defaultExpectation.paramPtrs.req = &req
	mmDo.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmDo
}

// Inspect accepts an inspector function that has same arguments as the DBConn.Do
func (mmDo *mDBConnMockDo) Inspect(f func(req *http.Request)) *mDBConnMockDo {
	if mmDo.mock.inspectFuncDo != nil {
		mmDo.mock.t.Fatalf("Inspect function is already set for DBConnMock.Do")
	}

	mmDo.mock.inspectFuncDo = f

	return mmDo
}

// Return sets up results that will be returned by DBConn.Do
func (mmDo *mDBConnMockDo) Return(rp1 *http.Response, err error) *DBConnMock {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("DBConnMock.Do mock is already set by Set")
	}

	if mmDo.defaultExpectation == nil {
		mmDo.defaultExpectation = &DBConnMockDoExpectation{mock: mmDo.mock}
	}
	mmDo.defaultExpectation.results = &DBConnMockDoResults{rp1, err}
	mmDo.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDo.mock
}

// Set uses given function f to mock the DBConn.Do method
func (mmDo *mDBConnMockDo) Set(f func(req *http.Request) (rp1 *http.Response, err error)) *DBConnMock {
	if mmDo.defaultExpectation != nil {
		mmDo.mock.t.Fatalf("Default expectation is already set for the DBConn.Do method")
	}

	if len(mmDo.expectations) > 0 {
		mmDo.mock.t.Fatalf("Some expectations are already set for the DBConn.Do method")
	}

	mmDo.mock.funcDo = f
	mmDo.mock.funcDoOrigin = minimock.CallerInfo(1)
	return mmDo.mock
}

// When sets expectation for the DBConn.Do which will trigger the result defined by the following
// Then helper
func (mmDo *mDBConnMockDo) When(req *http.Request) *DBConnMockDoExpectation {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("DBConnMock.Do mock is already set by Set")
	}

	expectation := &DBConnMockDoExpectation{
		mock:               mmDo.mock,
		params:             &DBConnMockDoParams{req},
		expectationOrigins: DBConnMockDoExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDo.expectations = append(mmDo.expectations, expectation)
	return expectation
}

// Then sets up DBConn.Do return parameters for the expectation previously defined by the When method
func (e *DBConnMockDoExpectation) Then(rp1 *http.Response, err error) *DBConnMock {
	e.results = &DBConnMockDoResults{rp1, err}
	return e.mock
}

// Times sets number of times DBConn.Do should be invoked
func (mmDo *mDBConnMockDo) Times(n uint64) *mDBConnMockDo {
	if n == 0 {
		mmDo.mock.t.Fatalf("Times of DBConnMock.Do mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDo.expectedInvocations, n)
	mmDo.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDo
}

func (mmDo *mDBConnMockDo) invocationsDone() bool {
	if len(mmDo.expectations) == 0 && mmDo.defaultExpectation == nil && mmDo.mock.funcDo == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDo.mock.afterDoCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDo.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Do implements DBConn
func (mmDo *DBConnMock) Do(req *http.Request) (rp1 *http.Response, err error) {
	mm_atomic.AddUint64(&mmDo.beforeDoCounter, 1)
	defer mm_atomic.AddUint64(&mmDo.afterDoCounter, 1)

	mmDo.t.Helper()

	if mmDo.inspectFuncDo != nil {
		mmDo.inspectFuncDo(req)
	}

	mm_params := DBConnMockDoParams{req}

	// Record call args
	mmDo.DoMock.mutex.Lock()
	mmDo.DoMock.callArgs = append(mmDo.DoMock.callArgs, &mm_params)
	mmDo.DoMock.mutex.Unlock()

	for _, e := range mmDo.DoMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.rp1, e.results.err
		}
	}

	if mmDo.DoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDo.DoMock.defaultExpectation.Counter, 1)
		mm_want := mmDo.DoMock.defaultExpectation.params
		mm_want_ptrs := mmDo.DoMock.defaultExpectation.paramPtrs

		mm_got := DBConnMockDoParams{req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmDo.t.Errorf("DBConnMock.Do got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDo.DoMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDo.t.Errorf("DBConnMock.Do got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDo.DoMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDo.DoMock.defaultExpectation.results
		if mm_results == nil {
			mmDo.t.Fatal("No results are set for the DBConnMock.Do")
		}
		return (*mm_results).rp1, (*mm_results).err
	}
	if mmDo.funcDo != nil {
		return mmDo.funcDo(req)
	}
	mmDo.t.Fatalf("Unexpected call to DBConnMock.Do. %v", req)
	return
}

// DoAfterCounter returns a count of finished DBConnMock.Do invocations
func (mmDo *DBConnMock) DoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDo.afterDoCounter)
}

// DoBeforeCounter returns a count of DBConnMock.Do invocations
func (mmDo *DBConnMock) DoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDo.beforeDoCounter)
}

// Calls returns a list of arguments used in each call to DBConnMock.Do.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDo *mDBConnMockDo) Calls() []*DBConnMockDoParams {
	mmDo.mutex.RLock()

	argCopy := make([]*DBConnMockDoParams, len(mmDo.callArgs))
	copy(argCopy, mmDo.callArgs)

	mmDo.mutex.RUnlock()

	return argCopy
}

// MinimockDoDone returns true if the count of the Do invocations corresponds
// the number of defined expectations
func (m *DBConnMock) MinimockDoDone() bool {
	if m.DoMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DoMock.invocationsDone()
}

// MinimockDoInspect logs each unmet expectation
func (m *DBConnMock) MinimockDoInspect() {
	for _, e := range m.DoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to DBConnMock.Do at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDoCounter := mm_atomic.LoadUint64(&m.afterDoCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DoMock.defaultExpectation != nil && afterDoCounter < 1 {
		if m.DoMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to DBConnMock.Do at\n%s", m.DoMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to DBConnMock.Do at\n%s with params: %#v", m.DoMock.defaultExpectation.expectationOrigins.origin, *m.DoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDo != nil && afterDoCounter < 1 {
		m.t.Errorf("Expected call to DBConnMock.Do at\n%s", m.funcDoOrigin)
	}

	if !m.DoMock.invocationsDone() && afterDoCounter > 0 {
		m.t.Errorf("Expected %d calls to DBConnMock.Do at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DoMock.expectedInvocations), m.DoMock.expectedInvocationsOrigin, afterDoCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *DBConnMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDoInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *DBConnMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *DBConnMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDoDone()
}
